// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBA.ExternalDataAccess.Concrete.EntityFramework.Contexts;

#nullable disable

namespace SBA.ExternalDataAccess.Migrations
{
    [DbContext(typeof(ExternalAppDbContext))]
    [Migration("20240406014344_propertiesAreCorrected")]
    partial class propertiesAreCorrected
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.AiDataHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("DataType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("JsonTextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AiDataHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.AverageStatisticsHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Average_FT_Corners_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Corners_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Shut_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Shut_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_HT_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_HT_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Away_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Away_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<int>("BySideType")
                        .HasColumnType("int");

                    b.Property<int>("Corner_7_5_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("Corner_7_5_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("Corner_8_5_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("Corner_8_5_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("Corner_9_5_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("Corner_9_5_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_3_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_4_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_5_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_3_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_4_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_5_5_Over")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("FT_15_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_15_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG_Home")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("HT_15_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("HT_15_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("HT_GG_Away")
                        .HasColumnType("int");

                    b.Property<int>("HT_GG_Home")
                        .HasColumnType("int");

                    b.Property<int>("Home_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Home_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_X2")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X2")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X2")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X2")
                        .HasColumnType("int");

                    b.Property<int>("LeagueStaisticsHolderId")
                        .HasColumnType("int");

                    b.Property<int>("MatchIdentifierId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("SH_05_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("SH_05_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("SH_15_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("SH_15_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("SH_GG_Away")
                        .HasColumnType("int");

                    b.Property<int>("SH_GG_Home")
                        .HasColumnType("int");

                    b.Property<Guid>("UniqueIdentity")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeagueStaisticsHolderId");

                    b.ToTable("AverageStatisticsHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.ComparisonStatisticsHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Average_FT_Conceded_Goals_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Conceded_Goals_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Corners_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Corners_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Shut_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Shut_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Conceded_Goals_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Conceded_Goals_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_HT_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Conceded_Goals_AwayTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Conceded_Goals_HomeTeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Goals_AwayTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Goals_HomeTeam")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Away_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Away_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<int>("BySideType")
                        .HasColumnType("int");

                    b.Property<int>("Corner_7_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_8_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_9_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_3_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_4_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Away_5_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_3_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_4_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Home_5_5_Over")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("HT_GG")
                        .HasColumnType("int");

                    b.Property<int>("Home_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Home_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X")
                        .HasColumnType("int");

                    b.Property<int>("LeagueStaisticsHolderId")
                        .HasColumnType("int");

                    b.Property<int>("MatchIdentifierId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("SH_GG")
                        .HasColumnType("int");

                    b.Property<Guid>("UniqueIdentity")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeagueStaisticsHolderId");

                    b.ToTable("ComparisonStatisticsHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<bool>("IsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchIdentifierId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.HasKey("Id");

                    b.HasIndex("MatchIdentifierId");

                    b.ToTable("Forecasts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.LeagueStatisticsHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountFound")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime>("DateOfAnalyse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Local));

                    b.Property<decimal>("FT_GoalsAverage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("FT_Over15_Percentage")
                        .HasColumnType("int");

                    b.Property<int>("FT_Over25_Percentage")
                        .HasColumnType("int");

                    b.Property<int>("FT_Over35_Percentage")
                        .HasColumnType("int");

                    b.Property<int>("GG_Percentage")
                        .HasColumnType("int");

                    b.Property<decimal>("HT_GoalsAverage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("HT_Over05_Percentage")
                        .HasColumnType("int");

                    b.Property<int>("HT_Over15_Percentage")
                        .HasColumnType("int");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<decimal>("SH_GoalsAverage")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("SH_Over05_Percentage")
                        .HasColumnType("int");

                    b.Property<int>("SH_Over15_Percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeagueStatisticsHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.MatchIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("FT_Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HT_Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("MatchDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("MatchIdentifiers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.MatchOddsHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Away_1_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Away_1_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Away_2_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Away_2_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Away_3_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Away_3_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Away_4_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Away_4_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Cards_3_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cards_3_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cards_4_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cards_4_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cards_5_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cards_5_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<decimal>("Even_Tek")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_1_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_1_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_2_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_2_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_3_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_3_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_4_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_4_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_5_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_5_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Corners_Range_0_8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Corners_Range_12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Corners_Range_9_11")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Double_1_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Double_1_X")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Double_X_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Over_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Over_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Over_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Over_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Under_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Under_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Under_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Draw_Under_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_GG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_MoreCorner_Away")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_MoreCorner_Equal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_MoreCorner_Home")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_NG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Over_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Over_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Over_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Over_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Under_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Under_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Under_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win1_Under_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Over_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Over_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Over_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Over_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Under_15")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Under_25")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Under_35")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FT_Win2_Under_45")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FirstCorner_Away")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstCorner_Home")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstCorner_Never")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstGoal_Away")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FirstGoal_Home")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("FirstGoal_None")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Goals01")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Goals23")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Goals45")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Goals6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_0_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_0_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_1_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_1_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_2_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_2_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_Corners_10_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_10_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_4_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_4_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_8_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_8_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_9_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_9_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_Range_0_4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_Range_5_6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Corners_Range_7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Double_1_2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Double_1_X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Double_X_2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Draw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_FT_Away_Away")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Away_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Away_Home")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Draw_Away")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Draw_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Draw_Home")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Home_Away")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Home_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_FT_Home_Home")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("HT_MoreCorner_Away")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_MoreCorner_Equal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_MoreCorner_Home")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Win1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Win2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Handicap_01_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_01_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_01_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_02_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_02_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_02_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_03_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_03_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_03_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_04_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_04_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_04_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_10_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_10_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_10_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_20_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_20_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_20_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_30_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_30_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_30_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_40_Draw")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_40_Win1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Handicap_40_Win2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_1_5_Over")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Home_1_5_Under")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Home_2_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_2_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_3_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_3_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_4_5_Over")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Home_4_5_Under")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<decimal>("MoreGoal_1st")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("MoreGoal_2nd")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("MoreGoal_Equal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Odd_Cut")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("SH_Draw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SH_Win1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SH_Win2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Score_0_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_3")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_4")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_5")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_0_6")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_3")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_4")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_1_5")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_2_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_2_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_2_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_2_3")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_2_4")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_3_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_3_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_3_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_3_3")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_4_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_4_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_4_2")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_5_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_5_1")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_6_0")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<decimal>("Score_Other")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasDefaultValue(-1m);

                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("MatchOddsHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.PossibleForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<int>("UpdateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("PossibleForecasts", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.StatisticInfoHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AwayPercent")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("AwayValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BySideType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<decimal>("HomePercent")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("HomeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<int>("StatisticType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatisticInfoHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.TeamPerformanceStatisticsHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Average_FT_Conceded_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Corners_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Shut_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Conceded_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_HT_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Conceded_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("Average_SH_Goals_Team")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("BySideType")
                        .HasColumnType("int");

                    b.Property<int>("Corner_7_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_8_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_9_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Team_3_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Team_4_5_Over")
                        .HasColumnType("int");

                    b.Property<int>("Corner_Team_5_5_Over")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("HT_GG")
                        .HasColumnType("int");

                    b.Property<int>("HomeOrAway")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_Win")
                        .HasColumnType("int");

                    b.Property<int>("Is_Corner_FT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X")
                        .HasColumnType("int");

                    b.Property<int>("LeagueStaisticsHolderId")
                        .HasColumnType("int");

                    b.Property<int>("MatchIdentifierId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("SH_GG")
                        .HasColumnType("int");

                    b.Property<int>("Team_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_HT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Team_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_SH_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Team_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<Guid>("UniqueIdentity")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeagueStaisticsHolderId");

                    b.ToTable("TeamPerformanceStatisticsHolders", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.SqlEntities.FunctionViewProcModels.MatchForecastFM", b =>
                {
                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryLeague")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FT_Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HT_Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchIdentityId")
                        .HasColumnType("int");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.ToTable("MatchForecastsFM");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.AverageStatisticsHolder", b =>
                {
                    b.HasOne("Core.Entities.Concrete.ExternalDbEntities.LeagueStatisticsHolder", "LeagueStatisticsHolder")
                        .WithMany("AverageStatisticsHolders")
                        .HasForeignKey("LeagueStaisticsHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueStatisticsHolder");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.ComparisonStatisticsHolder", b =>
                {
                    b.HasOne("Core.Entities.Concrete.ExternalDbEntities.LeagueStatisticsHolder", "LeagueStatisticsHolder")
                        .WithMany("ComparisonStatisticsHolders")
                        .HasForeignKey("LeagueStaisticsHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueStatisticsHolder");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.Forecast", b =>
                {
                    b.HasOne("Core.Entities.Concrete.ExternalDbEntities.MatchIdentifier", "MatchIdentifier")
                        .WithMany("Forecasts")
                        .HasForeignKey("MatchIdentifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchIdentifier");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.TeamPerformanceStatisticsHolder", b =>
                {
                    b.HasOne("Core.Entities.Concrete.ExternalDbEntities.LeagueStatisticsHolder", "LeagueStatisticsHolder")
                        .WithMany("TeamPerformanceStatisticsHolders")
                        .HasForeignKey("LeagueStaisticsHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeagueStatisticsHolder");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.LeagueStatisticsHolder", b =>
                {
                    b.Navigation("AverageStatisticsHolders");

                    b.Navigation("ComparisonStatisticsHolders");

                    b.Navigation("TeamPerformanceStatisticsHolders");
                });

            modelBuilder.Entity("Core.Entities.Concrete.ExternalDbEntities.MatchIdentifier", b =>
                {
                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
