//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ResourceTr", typeof(ResourceTr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner Beraberlik Yüzdesi.
        /// </summary>
        internal static string Cor_X {
            get {
                return ResourceManager.GetString("Cor_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner 7.5 Üst Yüzdesi.
        /// </summary>
        internal static string Cor7_5_FT {
            get {
                return ResourceManager.GetString("Cor7_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner 8.5 Üst Yüzdesi.
        /// </summary>
        internal static string Cor8_5_FT {
            get {
                return ResourceManager.GetString("Cor8_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner 9.5 Üst Yüzdesi.
        /// </summary>
        internal static string Cor9_5_FT {
            get {
                return ResourceManager.GetString("Cor9_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maçta 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string FT_15 {
            get {
                return ResourceManager.GetString("FT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS 1,5 Ü.
        /// </summary>
        internal static string FT_15_O_FC {
            get {
                return ResourceManager.GetString("FT_15_O_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maçta 2.5 Üst Yüzdesi.
        /// </summary>
        internal static string FT_25 {
            get {
                return ResourceManager.GetString("FT_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS 2,5 Ü.
        /// </summary>
        internal static string FT_25_O_FC {
            get {
                return ResourceManager.GetString("FT_25_O_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maçta 3.5 Üst Yüzdesi.
        /// </summary>
        internal static string FT_35 {
            get {
                return ResourceManager.GetString("FT_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşılıklı Gol Yüzdesi.
        /// </summary>
        internal static string FT_GG {
            get {
                return ResourceManager.GetString("FT_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS KG Var.
        /// </summary>
        internal static string FT_GG_FC {
            get {
                return ResourceManager.GetString("FT_GG_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beraberlik Yüzdesi.
        /// </summary>
        internal static string FT_X {
            get {
                return ResourceManager.GetString("FT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı 0.5 Üst Yüzdesi.
        /// </summary>
        internal static string HT_05 {
            get {
                return ResourceManager.GetString("HT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string HT_15 {
            get {
                return ResourceManager.GetString("HT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı Karşılıklı Gol Yüzdesi.
        /// </summary>
        internal static string HT_GG {
            get {
                return ResourceManager.GetString("HT_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY Ev Galibiyet.
        /// </summary>
        internal static string HT_Win_1_FC {
            get {
                return ResourceManager.GetString("HT_Win_1_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY Dep Galibiyet.
        /// </summary>
        internal static string HT_Win_2_FC {
            get {
                return ResourceManager.GetString("HT_Win_2_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı Beraberlik Yüzdesi.
        /// </summary>
        internal static string HT_X {
            get {
                return ResourceManager.GetString("HT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Corner_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Corner_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maçta Gol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı Gol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_HT {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı Gol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_SH {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şut Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Shut_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Shut_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaleyi Bulan Şut Ortalaması.
        /// </summary>
        internal static string Ind_Avg_ShutOnTrg_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_ShutOnTrg_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korner Galibiyet Yüzdesi.
        /// </summary>
        internal static string Ind_Cor_Win {
            get {
                return ResourceManager.GetString("Ind_Cor_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 3.5 Üst Korner Yüzdesi.
        /// </summary>
        internal static string Ind_Cor3_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor3_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 4.5 Üst Korner Yüzdesi.
        /// </summary>
        internal static string Ind_Cor4_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor4_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 5.5 Üst Korner Yüzdesi.
        /// </summary>
        internal static string Ind_Cor5_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor5_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 0.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_FT_05 {
            get {
                return ResourceManager.GetString("Ind_FT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_FT_15 {
            get {
                return ResourceManager.GetString("Ind_FT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galibiyet Yüzdesi.
        /// </summary>
        internal static string Ind_FT_Win {
            get {
                return ResourceManager.GetString("Ind_FT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın İlk Yarı 0.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_HT_05 {
            get {
                return ResourceManager.GetString("Ind_HT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın İlk Yarı 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_HT_15 {
            get {
                return ResourceManager.GetString("Ind_HT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlk Yarı Galibiyet Yüzdesi.
        /// </summary>
        internal static string Ind_HT_Win {
            get {
                return ResourceManager.GetString("Ind_HT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topla Oynama Yüzdesi.
        /// </summary>
        internal static string Ind_Poss_FT {
            get {
                return ResourceManager.GetString("Ind_Poss_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın İkinci Yarı 0.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_SH_05 {
            get {
                return ResourceManager.GetString("Ind_SH_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın İkinci Yarı 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string Ind_SH_15 {
            get {
                return ResourceManager.GetString("Ind_SH_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı Galibiyet Yüzdesi.
        /// </summary>
        internal static string Ind_SH_Win {
            get {
                return ResourceManager.GetString("Ind_SH_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her-Hangi Yarı Galibiyet Yüzdesi.
        /// </summary>
        internal static string Ind_WinAny {
            get {
                return ResourceManager.GetString("Ind_WinAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı 0.5 Üst Yüzdesi.
        /// </summary>
        internal static string SH_05 {
            get {
                return ResourceManager.GetString("SH_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı 1.5 Üst Yüzdesi.
        /// </summary>
        internal static string SH_15 {
            get {
                return ResourceManager.GetString("SH_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı Karşılıklı Gol Yüzdesi.
        /// </summary>
        internal static string SH_GG {
            get {
                return ResourceManager.GetString("SH_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İY Ev Galibiyet.
        /// </summary>
        internal static string SH_Win_1_FC {
            get {
                return ResourceManager.GetString("SH_Win_1_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İY Dep Galibiyet.
        /// </summary>
        internal static string SH_Win_2_FC {
            get {
                return ResourceManager.GetString("SH_Win_2_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Yarı Beraberlik Yüzdesi.
        /// </summary>
        internal static string SH_X {
            get {
                return ResourceManager.GetString("SH_X", resourceCulture);
            }
        }
    }
}
