//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ResourceAz", typeof(ResourceAz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi Bərabərlik Faizi.
        /// </summary>
        internal static string Cor_X {
            get {
                return ResourceManager.GetString("Cor_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi 7.5 Üst Faizi.
        /// </summary>
        internal static string Cor7_5_FT {
            get {
                return ResourceManager.GetString("Cor7_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi 8.5 Üst Faizi.
        /// </summary>
        internal static string Cor8_5_FT {
            get {
                return ResourceManager.GetString("Cor8_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi 9.5 Üst Faizi.
        /// </summary>
        internal static string Cor9_5_FT {
            get {
                return ResourceManager.GetString("Cor9_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matçda 1.5 Üst Faizi.
        /// </summary>
        internal static string FT_15 {
            get {
                return ResourceManager.GetString("FT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyun Nəticəsi 1,5 Üst.
        /// </summary>
        internal static string FT_15_O_FC {
            get {
                return ResourceManager.GetString("FT_15_O_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matçda 2.5 Üst Faizi.
        /// </summary>
        internal static string FT_25 {
            get {
                return ResourceManager.GetString("FT_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyun Nəticəsi 2,5 Üst.
        /// </summary>
        internal static string FT_25_O_FC {
            get {
                return ResourceManager.GetString("FT_25_O_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matçda 3.5 Üst Faizi.
        /// </summary>
        internal static string FT_35 {
            get {
                return ResourceManager.GetString("FT_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matçda Qol-Qol Faizi.
        /// </summary>
        internal static string FT_GG {
            get {
                return ResourceManager.GetString("FT_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyun Nəticəsi Qarşılıqlı qol var.
        /// </summary>
        internal static string FT_GG_FC {
            get {
                return ResourceManager.GetString("FT_GG_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bərabərlik Faizi.
        /// </summary>
        internal static string FT_X {
            get {
                return ResourceManager.GetString("FT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə 0.5 Üst Faizi.
        /// </summary>
        internal static string HT_05 {
            get {
                return ResourceManager.GetString("HT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə 1.5 Üst Faizi.
        /// </summary>
        internal static string HT_15 {
            get {
                return ResourceManager.GetString("HT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə Qol-Qol Faizi.
        /// </summary>
        internal static string HT_GG {
            get {
                return ResourceManager.GetString("HT_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birinci Hissə Ev sahibi takım qələbə.
        /// </summary>
        internal static string HT_Win_1_FC {
            get {
                return ResourceManager.GetString("HT_Win_1_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birinci Hissə Səfər komanda qələbə.
        /// </summary>
        internal static string HT_Win_2_FC {
            get {
                return ResourceManager.GetString("HT_Win_2_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə Bərabərlik Faizi.
        /// </summary>
        internal static string HT_X {
            get {
                return ResourceManager.GetString("HT_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyun Ərzində Yediyi Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Conc_Goal_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Conc_Goal_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə Yediyi Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Conc_Goal_HT {
            get {
                return ResourceManager.GetString("Ind_Avg_Conc_Goal_HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə Yediyi Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Conc_Goal_SH {
            get {
                return ResourceManager.GetString("Ind_Avg_Conc_Goal_SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi ortalaması.
        /// </summary>
        internal static string Ind_Avg_Corner_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Corner_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qapıçının Qurtarış Ortalaması.
        /// </summary>
        internal static string Ind_Avg_GK_Saves_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_GK_Saves_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_HT {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə Qol Ortalaması.
        /// </summary>
        internal static string Ind_Avg_Goal_SH {
            get {
                return ResourceManager.GetString("Ind_Avg_Goal_SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qapıya zərbə ortalaması.
        /// </summary>
        internal static string Ind_Avg_Shut_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_Shut_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəqiq zərbə ortalaması.
        /// </summary>
        internal static string Ind_Avg_ShutOnTrg_FT {
            get {
                return ResourceManager.GetString("Ind_Avg_ShutOnTrg_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künc zərbəsi Qalibiyyət Faizi.
        /// </summary>
        internal static string Ind_Cor_Win {
            get {
                return ResourceManager.GetString("Ind_Cor_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 3.5 Üst Künc Zərbə Faizi.
        /// </summary>
        internal static string Ind_Cor3_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor3_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 4.5 Üst Künc Zərbə Faizi.
        /// </summary>
        internal static string Ind_Cor4_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor4_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 5.5 Üst Künc Zərbə Faizi.
        /// </summary>
        internal static string Ind_Cor5_5_FT {
            get {
                return ResourceManager.GetString("Ind_Cor5_5_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 0.5 Üst Faizi.
        /// </summary>
        internal static string Ind_FT_05 {
            get {
                return ResourceManager.GetString("Ind_FT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 1.5 Üst Faizi.
        /// </summary>
        internal static string Ind_FT_15 {
            get {
                return ResourceManager.GetString("Ind_FT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qalibiyyət Faizi.
        /// </summary>
        internal static string Ind_FT_Win {
            get {
                return ResourceManager.GetString("Ind_FT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 1-ci Hissə 0.5 Üst Faizi.
        /// </summary>
        internal static string Ind_HT_05 {
            get {
                return ResourceManager.GetString("Ind_HT_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 1-ci Hissə 1.5 Üst Faizi.
        /// </summary>
        internal static string Ind_HT_15 {
            get {
                return ResourceManager.GetString("Ind_HT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-ci Hissə Qalibiyyət Faizi.
        /// </summary>
        internal static string Ind_HT_Win {
            get {
                return ResourceManager.GetString("Ind_HT_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topla Oynama Faizi.
        /// </summary>
        internal static string Ind_Poss_FT {
            get {
                return ResourceManager.GetString("Ind_Poss_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 2-ci Hissə 0.5 Üst Faizi.
        /// </summary>
        internal static string Ind_SH_05 {
            get {
                return ResourceManager.GetString("Ind_SH_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımın 2-ci Hissə 1.5 Üst Faizi.
        /// </summary>
        internal static string Ind_SH_15 {
            get {
                return ResourceManager.GetString("Ind_SH_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə Qalibiyyət Faizi.
        /// </summary>
        internal static string Ind_SH_Win {
            get {
                return ResourceManager.GetString("Ind_SH_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hər-Hansı Hissə Qələbə Faizi.
        /// </summary>
        internal static string Ind_WinAny {
            get {
                return ResourceManager.GetString("Ind_WinAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə 0.5 Üst Faizi.
        /// </summary>
        internal static string SH_05 {
            get {
                return ResourceManager.GetString("SH_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə 1.5 Üst Faizi.
        /// </summary>
        internal static string SH_15 {
            get {
                return ResourceManager.GetString("SH_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə Qol-Qol Faizi.
        /// </summary>
        internal static string SH_GG {
            get {
                return ResourceManager.GetString("SH_GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Hissə Ev sahibi takım qələbə.
        /// </summary>
        internal static string SH_Win_1_FC {
            get {
                return ResourceManager.GetString("SH_Win_1_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci Hissə Səfər takım qələbə.
        /// </summary>
        internal static string SH_Win_2_FC {
            get {
                return ResourceManager.GetString("SH_Win_2_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-ci Hissə Bərabərlik Faizi.
        /// </summary>
        internal static string SH_X {
            get {
                return ResourceManager.GetString("SH_X", resourceCulture);
            }
        }
    }
}
