// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SBA.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240804003759_extraHandlingForSystem")]
    partial class extraHandlingForSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.FilterResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayCornerCount")
                        .HasColumnType("int");

                    b.Property<int>("AwayFtGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("AwayHtGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("AwayPossesion")
                        .HasColumnType("int");

                    b.Property<int>("AwayShGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("AwayShotCount")
                        .HasColumnType("int");

                    b.Property<int>("AwayShotOnTargetCount")
                        .HasColumnType("int");

                    b.Property<bool>("Away_FT_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_FT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_HT_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_HT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_SH_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_SH_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Away_Win_Any_Half")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_7_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_8_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_9_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Away_3_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Away_4_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Away_5_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Home_3_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Home_4_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Corner_Home_5_5_Over")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(6401));

                    b.Property<bool>("FT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("FT_2_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("FT_3_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("FT_GG")
                        .HasColumnType("bit");

                    b.Property<int>("FT_Result")
                        .HasColumnType("int");

                    b.Property<int>("FT_TotalBetween")
                        .HasColumnType("int");

                    b.Property<bool>("HT_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("HT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<int>("HT_FT_Result")
                        .HasColumnType("int");

                    b.Property<bool>("HT_GG")
                        .HasColumnType("bit");

                    b.Property<int>("HT_Result")
                        .HasColumnType("int");

                    b.Property<int>("HomeCornerCount")
                        .HasColumnType("int");

                    b.Property<int>("HomeFtGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("HomeHtGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("HomePossesion")
                        .HasColumnType("int");

                    b.Property<int>("HomeShGoalCount")
                        .HasColumnType("int");

                    b.Property<int>("HomeShotCount")
                        .HasColumnType("int");

                    b.Property<int>("HomeShotOnTargetCount")
                        .HasColumnType("int");

                    b.Property<bool>("Home_FT_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_FT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_HT_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_HT_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_SH_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_SH_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("Home_Win_Any_Half")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCornerFound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPossesionFound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShotFound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShotOnTargetFound")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Corner_FT_Win1")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Corner_FT_Win2")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Corner_FT_X")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_FT_Win1")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_FT_Win2")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_FT_X")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_HT_Win1")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_HT_Win2")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_HT_X")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_SH_Win1")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_SH_Win2")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_SH_X")
                        .HasColumnType("bit");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(6401));

                    b.Property<int>("MoreGoalsBetweenTimes")
                        .HasColumnType("int");

                    b.Property<bool>("SH_0_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("SH_1_5_Over")
                        .HasColumnType("bit");

                    b.Property<bool>("SH_GG")
                        .HasColumnType("bit");

                    b.Property<int>("SH_Result")
                        .HasColumnType("int");

                    b.Property<int>("SerialUniqueID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FilterResults");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Local).AddTicks(8490));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.MatchBet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(903));

                    b.Property<decimal>("FTDraw_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FTWin1_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FTWin2_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_01_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_23_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_45_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_6_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_GG_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FT_Match_Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FT_NG_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Over_1_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Over_2_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Over_3_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Under_1_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Under_2_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FT_Under_3_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HTDraw_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HTWin1_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HTWin2_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HT_Match_Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HT_Over_1_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HT_Under_1_5_Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCountryLeagueUpdated")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(903));

                    b.Property<int>("SerialUniqueID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatchBets");
                });

            modelBuilder.Entity("Core.Entities.Concrete.PerformanceOverall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Average_FT_Conceded_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Conceded_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_GK_Saves_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_ShutOnTarget_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Shut_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_FT_Shut_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Conceded_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Conceded_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_HT_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Conceded_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Conceded_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Goals_Away_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Average_SH_Goals_Home_Team")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Away_Team_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Team_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Team_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Team_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Away_Team_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Away_Team_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(3668));

                    b.Property<int>("FT_15_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_15_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_25_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_35_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG_Away")
                        .HasColumnType("int");

                    b.Property<int>("FT_GG_Home")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("HT_05_Over_Home")
                        .HasColumnType("int");

                    b.Property<string>("Hashed_Compact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed_Detailed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed_Full_Detailed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed_Less_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed_Simple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Team_FT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Team_FT_15_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Team_HT_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Team_Possesion")
                        .HasColumnType("int");

                    b.Property<int>("Home_Team_SH_05_Over")
                        .HasColumnType("int");

                    b.Property<int>("Home_Team_Win_Any_Half")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Is_FT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_FT_X2")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_HT_X2")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win1")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_Win2")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X1")
                        .HasColumnType("int");

                    b.Property<int>("Is_SH_X2")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 263, DateTimeKind.Unspecified).AddTicks(3668));

                    b.Property<int>("SH_05_Over_Away")
                        .HasColumnType("int");

                    b.Property<int>("SH_05_Over_Home")
                        .HasColumnType("int");

                    b.Property<int>("SerialUniqueID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PerformanceOveralls");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.BetSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptedDivider")
                        .HasColumnType("int");

                    b.Property<decimal>("AcceptedOdd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(1237));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxBundleCount")
                        .HasColumnType("int");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(1237));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StepsGoalCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BetSystems");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Bundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BundlePriority")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(180));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(180));

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.ComboBet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetType")
                        .HasColumnType("int");

                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(3101));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInsuredBet")
                        .HasColumnType("bit");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(3101));

                    b.Property<int>("PotentialWinningPercent")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalOdd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.ToTable("ComboBets");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.ComboBetPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComboBetId")
                        .HasColumnType("int");

                    b.Property<int>("PredictionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboBetId");

                    b.HasIndex("PredictionId");

                    b.ToTable("ComboBetPredictions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysingProbableMatchCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(5734));

                    b.Property<int>("ForecastId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 265, DateTimeKind.Unspecified).AddTicks(5734));

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProbableWinPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.SavedStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetSystemId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(7289));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(7289));

                    b.Property<int>("StartingStepId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BetSystemId");

                    b.ToTable("SavedSteps");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetSystemId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(4171));

                    b.Property<decimal>("InsuredBetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedFrom")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedTo")
                        .HasColumnType("int");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System.Admin");

                    b.Property<DateTime>("ModifiedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 8, 4, 4, 37, 58, 264, DateTimeKind.Unspecified).AddTicks(4171));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BetSystemId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Bundle", b =>
                {
                    b.HasOne("Core.Entities.Concrete.System.BetSystem", "System")
                        .WithMany("Bundles")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.ComboBet", b =>
                {
                    b.HasOne("Core.Entities.Concrete.System.Bundle", "Bundle")
                        .WithMany("ComboBets")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.ComboBetPrediction", b =>
                {
                    b.HasOne("Core.Entities.Concrete.System.ComboBet", "ComboBet")
                        .WithMany("ComboBetPredictions")
                        .HasForeignKey("ComboBetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.System.Prediction", "Prediction")
                        .WithMany("ComboBetPredictions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComboBet");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.SavedStep", b =>
                {
                    b.HasOne("Core.Entities.Concrete.System.BetSystem", "System")
                        .WithMany("SavedSteps")
                        .HasForeignKey("BetSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Step", b =>
                {
                    b.HasOne("Core.Entities.Concrete.System.BetSystem", "System")
                        .WithMany("Steps")
                        .HasForeignKey("BetSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.BetSystem", b =>
                {
                    b.Navigation("Bundles");

                    b.Navigation("SavedSteps");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Bundle", b =>
                {
                    b.Navigation("ComboBets");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.ComboBet", b =>
                {
                    b.Navigation("ComboBetPredictions");
                });

            modelBuilder.Entity("Core.Entities.Concrete.System.Prediction", b =>
                {
                    b.Navigation("ComboBetPredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
